#!/usr/bin/env bash
set -euo pipefail

cd /mnt/infini-data/test/BeyondMimic

RUN_TAG="${1:-rootxy0_robotjoint_refresh_env65536_$(date +%Y%m%d_%H%M%S)}"
LOG_DIR="/mnt/infini-data/test/BeyondMimic/logs/tracking_hub_singleleg_paper_contract_ppo_training_run_${RUN_TAG}"
mkdir -p "${LOG_DIR}"

export PYTHONUNBUFFERED=1
export BM_REFRESH_MOTION_COMMAND_TARGETS=1
export BM_HUB_SINGLELEG_RUN_TAG="${RUN_TAG}"
export BM_HUB_SINGLELEG_TARGET_GPUS="${BM_HUB_SINGLELEG_TARGET_GPUS:-5,6}"
export BM_HUB_SINGLELEG_MOTION_NPZ="${BM_HUB_SINGLELEG_MOTION_NPZ:-/mnt/infini-data/test/BeyondMimic/res/tracking/stage1_short_motion_recentered_bundle_robot_joint_order/motions/hub_singleleg_video_single_leg_stand_1_rootxy0/motion.npz}"
export BM_HUB_SINGLELEG_NUM_ENVS_PER_RANK="${BM_HUB_SINGLELEG_NUM_ENVS_PER_RANK:-65536}"
export BM_HUB_SINGLELEG_MAX_ITERATIONS="${BM_HUB_SINGLELEG_MAX_ITERATIONS:-3000}"
export BM_HUB_SINGLELEG_SAVE_INTERVAL="${BM_HUB_SINGLELEG_SAVE_INTERVAL:-250}"
export BM_HUB_SINGLELEG_MIN_FREE_MB="${BM_HUB_SINGLELEG_MIN_FREE_MB:-10000}"
export BM_HUB_SINGLELEG_MAX_BUSY_UTIL="${BM_HUB_SINGLELEG_MAX_BUSY_UTIL:-90}"
export BM_HUB_SINGLELEG_SEED="${BM_HUB_SINGLELEG_SEED:-20260931}"
export BM_HUB_SINGLELEG_ADAPTIVE_KERNEL_SIZE="${BM_HUB_SINGLELEG_ADAPTIVE_KERNEL_SIZE:-3}"
export BM_PHYSX_GPU_MAX_RIGID_CONTACT_COUNT="${BM_PHYSX_GPU_MAX_RIGID_CONTACT_COUNT:-16777216}"
export BM_PHYSX_GPU_MAX_RIGID_PATCH_COUNT="${BM_PHYSX_GPU_MAX_RIGID_PATCH_COUNT:-1048576}"
export BM_PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY="${BM_PHYSX_GPU_FOUND_LOST_PAIRS_CAPACITY:-4194304}"
export BM_PHYSX_GPU_FOUND_LOST_AGGREGATE_PAIRS_CAPACITY="${BM_PHYSX_GPU_FOUND_LOST_AGGREGATE_PAIRS_CAPACITY:-33554432}"
export BM_PHYSX_GPU_TOTAL_AGGREGATE_PAIRS_CAPACITY="${BM_PHYSX_GPU_TOTAL_AGGREGATE_PAIRS_CAPACITY:-4194304}"
export BM_PHYSX_GPU_COLLISION_STACK_SIZE="${BM_PHYSX_GPU_COLLISION_STACK_SIZE:-134217728}"
export BM_PHYSX_GPU_HEAP_CAPACITY="${BM_PHYSX_GPU_HEAP_CAPACITY:-134217728}"
export BM_PHYSX_GPU_TEMP_BUFFER_CAPACITY="${BM_PHYSX_GPU_TEMP_BUFFER_CAPACITY:-33554432}"

exec /mnt/infini-data/test/BeyondMimic/envs/bm_tracking/bin/python -u \
  /mnt/infini-data/test/BeyondMimic/reproduction/scripts/tracking_hub_singleleg_paper_contract_ppo_training_run.py
